# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

 pod'Alamofire','~> 1.2.0'
 pod'SwiftyJSON','~> 2.2.0'

target 'ShareTheBag' do

end

target 'ShareTheBagTests' do

end

